// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mlestimate
List mlestimate(NumericVector D, NumericVector x0, NumericMatrix ref, IntegerVector Itmax, NumericVector Tol);
RcppExport SEXP _tempoSig_mlestimate(SEXP DSEXP, SEXP x0SEXP, SEXP refSEXP, SEXP ItmaxSEXP, SEXP TolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ref(refSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Itmax(ItmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tol(TolSEXP);
    rcpp_result_gen = Rcpp::wrap(mlestimate(D, x0, ref, Itmax, Tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tempoSig_mlestimate", (DL_FUNC) &_tempoSig_mlestimate, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_tempoSig(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
